# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='member',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='color',
            field=models.CharField(choices=[('light-green', 'Light Green'), ('purple', 'Purple'), ('yellow', 'Yellow'), ('indigo', 'Indigo'), ('cyan', 'Cyan'), ('deep-orange', 'Deep Orange'), ('teal', 'Teal'), ('red', 'Red'), ('green', 'Green'), ('orange', 'Orange'), ('amber', 'Amber'), ('lime', 'Lime'), ('deep-purple', 'Deep Purple'), ('blue', 'Blue'), ('light-blue', 'Light Blue'), ('pink', 'Pink')], default='cyan', max_length=16),
        ),
    ]
