# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-17 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20161203_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='askers',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='givers',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='list',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='purchaser',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
        migrations.DeleteModel(
            name='WishListItem',
        ),
    ]
