# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 16:37
from __future__ import unicode_literals

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='place',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='key',
            field=models.CharField(db_index=True, default=book.models.default_key, max_length=32),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
